# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cmpwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_cmpwindow(object):
    def setupUi(self, cmpwindow):
        cmpwindow.setObjectName("cmpwindow")
        cmpwindow.resize(783, 510)
        self.widget = QtWidgets.QWidget(cmpwindow)
        self.widget.setGeometry(QtCore.QRect(10, 10, 261, 491))
        #self.widget.setStyleSheet("background-color: rgb(211, 215, 207);")
        self.widget.setObjectName("widget")
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setGeometry(QtCore.QRect(10, 40, 241, 25))
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(20, 80, 91, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 91, 17))
        self.label_2.setObjectName("label_2")
        self.listView = QtWidgets.QListWidget(self.widget)
        self.listView.setGeometry(QtCore.QRect(10, 110, 241, 371))
        self.listView.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.listView.setObjectName("listView")
        self.groupBox = QtWidgets.QGroupBox(cmpwindow)
        self.groupBox.setGeometry(QtCore.QRect(280, 0, 491, 501))
        self.groupBox.setStyleSheet("")
        self.groupBox.setObjectName("groupBox")
        self.textEdit = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit.setGeometry(QtCore.QRect(20, 220, 451, 261))
        self.textEdit.setStyleSheet("")
        self.textEdit.setObjectName("textEdit")
        self.widget_2 = QtWidgets.QWidget(self.groupBox)
        self.widget_2.setGeometry(QtCore.QRect(10, 40, 471, 80))
        self.widget_2.setObjectName("widget_2")
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 81, 17))
        self.label_3.setObjectName("label_3")
        self.label_6 = QtWidgets.QLabel(self.widget_2)
        self.label_6.setGeometry(QtCore.QRect(10, 50, 111, 17))
        self.label_6.setObjectName("label_6")
        self.label_simi1 = QtWidgets.QLabel(self.widget_2)
        self.label_simi1.setGeometry(QtCore.QRect(80, 50, 231, 20))
        self.label_simi1.setText("")
        self.label_simi1.setObjectName("label_simi1")
        self.label_file1 = QtWidgets.QLabel(self.widget_2)
        self.label_file1.setGeometry(QtCore.QRect(100, 10, 231, 20))
        self.label_file1.setText("")
        self.label_file1.setObjectName("label_file1")
        self.widget_3 = QtWidgets.QWidget(self.groupBox)
        self.widget_3.setGeometry(QtCore.QRect(10, 140, 471, 351))
        self.widget_3.setObjectName("widget_3")
        self.label_4 = QtWidgets.QLabel(self.widget_3)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 111, 17))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.widget_3)
        self.label_5.setGeometry(QtCore.QRect(10, 40, 111, 17))
        self.label_5.setObjectName("label_5")
        self.label_simi2 = QtWidgets.QLabel(self.widget_3)
        self.label_simi2.setGeometry(QtCore.QRect(80, 40, 231, 20))
        self.label_simi2.setText("")
        self.label_simi2.setObjectName("label_simi2")
        self.label_file2 = QtWidgets.QLabel(self.widget_3)
        self.label_file2.setGeometry(QtCore.QRect(130, 10, 251, 20))
        self.label_file2.setText("")
        self.label_file2.setObjectName("label_file2")
        self.widget_3.raise_()
        self.textEdit.raise_()
        self.widget_2.raise_()
        self.groupBox.raise_()
        self.widget.raise_()

        self.retranslateUi(cmpwindow)
        QtCore.QMetaObject.connectSlotsByName(cmpwindow)

    def retranslateUi(self, cmpwindow):
        _translate = QtCore.QCoreApplication.translate
        cmpwindow.setWindowTitle(_translate("cmpwindow", "样本库比对结果显示"))
        self.label.setText(_translate("cmpwindow", "比对样本库:"))
        self.label_2.setText(_translate("cmpwindow", "目标文件:"))
        self.groupBox.setTitle(_translate("cmpwindow", "比对结果"))
        self.label_3.setText(_translate("cmpwindow", "最相似文件:"))
        self.label_6.setText(_translate("cmpwindow", "相似度："))
        self.label_4.setText(_translate("cmpwindow", "当前选中文件:"))
        self.label_5.setText(_translate("cmpwindow", "相似度："))

